---
- name: Run backup process
  uri:
    url: '{{ aem_url }}/system/console/jmx/com.adobe.granite:type=Repository/op/startBackup/java.lang.String?target={{ backup_path }}'
    method: POST
    user: '{{ aem_username }}'
    password: '{{ aem_password }}'

- name: Check until backup is finished
  stat:
    path: '{{ backup_path }}'
  register: stat_result
  until: stat_result.stat.exists
  retries: 300
  delay: 20