---
- name: Backup and restore feature
  hosts: aem_instance
  roles:
  - role: aem-backup
  vars:
    aem_host: 'http://localhost'
    aws_s3_storage: false
    azure_blob_storage: false
    ftps_enabled: false