---
- name: Install packages
  yum:
    name: 
    - python3-pip
    - python3-dev
    - build-essential
    - libssl-dev
    - libffi-dev
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
    - lftp
    state: present
    update_cache: yes
  become: true